### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by pieceofduke** [mogenslund/liquid#10]
Didn't manage to start using this on Windows.
Got lein installed via chocolatey.
Could you please provide a manual for leiningen users?..

**Comment by mogenslund** [comment]
Hi Duke

Just to be sure what you are trying to do. Did you checkout the project and executed "lein run" or "lein run --jframe"? Or did you add Liquid to an existing project through Clojars? On Windows there is no console support. There it has to run in a JFrame or as a service that is accessible from a browser. (JFrame will probably be the best experience.) When I know what you did, I will find a Windows computer and see if I can reproduce it and write down the doc to cover that situation.

Best regards,
Mogens

**Comment by pieceofduke** [comment]
Oh, clone it. That'll do ) I will make a PR with readme edits, you'll see )

**Comment by pieceofduke** [comment]
Okay, so I followed this instruction on my Windows machine:
http://salza.dk/setupbasic.html up to step 5 ("clj -m liana.core" from
.../liq ).
I tried lein run, and it told me something about invalid project.clj, which
I don't have.
Maybe you have a preconfigured project.clj ? Or can come up with one?..
It's worth adding it to the instruction then.
If not, I'll try my best at it.

**Comment by mogenslund** [comment]
Try a project.clj like this:

```clojure
(defproject liana "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :source-paths ["./src"
                 "../proj/liquid/src"
                 "../proj/additives/src"]
  :dependencies [[org.clojure/clojure "1.9.0"]]
  :main ^:skip-aot liana.core
  :profiles {:uberjar {:aot :all}})
```

(Maybe paths needs to be more Windows-like)
Save it in the liana/liq folder.

Then execute: lein run --jframe

**Comment by pieceofduke** [comment]
This worked. I'll open new issue for the next question.
