### ISSUE TITLE
Going into prompt then typeahead

### ISSUE THREAD

**Issue by tom-adsfund** [mogenslund/liquid#18]
I ran some code using 'e', which then produced a long error message. Then I used C-space to go to the prompt buffer to look at the start of the message. But then when I press C-space to go back to the main window, the prompt is taken over by the typeahead.

Maybe I'm missing something?

**Comment by tom-adsfund** [comment]
I see I'm probably supposed to use C-o

**Comment by mogenslund** [comment]
Yes C-o and then maybe gg to go to the top.
If you press 1 in navigation mode the s-expression that will be evaluated using e will be highlighted. Press 1 again to remove the highlight. Pressing 2 will select the s-expression (but move the cursor as well)

**Comment by mogenslund** [comment]
Typing 'M' (Shift+m) will make a temporary buffer in the main window with a copy of the -prompt- buffer. It sometimes makes information easier to read. Typing just 'm' will open the previous buffer again.
If you like, you should try out terminology. It works very smooth together with Liquid compared to other terminals I have tried.

**Comment by tom-adsfund** [comment]
Thanks for the pointer about M.

I think diversity in what we're using might be useful. Terminology looks pretty interesting, but I used to use Terminator because it had very nice window support (in the Vim sense of Window), and then I was using Kitty because it was OpenGL (fast rendering), also has other nice features like images and ligatures... But now you mention Terminology, which has images (and more) but not OpenGL....

I'll install it just for fun, and see what I think!

**Comment by tom-adsfund** [comment]
@mogenslund actually very good! I'll continue using it for a while. Would be perfect if it supported ligatures too!

**Comment by tom-adsfund** [comment]
I was thinking, maybe C-space in the prompt window should open the typeahead in the main window?

**Comment by tom-adsfund** [comment]
Also, M should be in the docs! It's a pretty powerful command.

**Comment by mogenslund** [comment]
I see the problem with C-space in the prompt window. It has been fixed now.

**Comment by mogenslund** [comment]
Fixed
