### ISSUE TITLE
Move API doc to use Clojure doc tool

### ISSUE THREAD

**Issue by tom-adsfund** [mogenslund/liquid#20]
I find the plain text on the website very hard to read!

**Comment by mogenslund** [comment]
I did not know about the Clojure doc tool. I will take a look at that. Thank you.

**Comment by mogenslund** [comment]
Can you provide a link? I get all kinds of doc tools when using Google and do not know which is official or the best.

**Comment by tom-adsfund** [comment]
I thought I maybe should have linked to one.

The one I've seen used is Codox (https://github.com/weavejester/codox), which is used by Compojure, among others.

**Comment by mogenslund** [comment]
First attempt to use Codox:
[http://salza.dk/liquid](http://salza.dk/liquid)

**Comment by tom-adsfund** [comment]
Great. That gives a much clearer view over the whole code base, not just the core parts.

I'll close this as the prime aim has been achieved.
