### ISSUE TITLE
gg from bottom of large file slow

### ISSUE THREAD

**Issue by tom-adsfund** [mogenslund/liquid#24]
Large file: https://raw.githubusercontent.com/clojure/clojure/master/src/clj/clojure/core.clj

I'm not sure if there's an obvious way to speed this up.

**Comment by tom-adsfund** [comment]
(I was doing this to test a parser I was working on -- if you were wondering why someone would do this!)

**Comment by mogenslund** [comment]
Fix committed. I was doing a recalculation of "top of the window" all the way to the beginning of the buffer. For a file with 7000 lines that is around 150 very expensive and unnecessary recalculations. With that in mind I actually think the performance was quite impressive. Thanks for helping me fix that one.

**Comment by tom-adsfund** [comment]
Interesting reason for the slowness! I'll close this.
