### ISSUE TITLE
More weird insert errors

### ISSUE THREAD

**Issue by tom-adsfund** [mogenslund/liquid#26]
As in https://github.com/mogenslund/liquid/issues/17 I was doing some editing in Liquid, this time in Terminology, and a spurious partial escape sequence was inserted into the text while I was moving the cursor.

I don't know how to recreate this this time, but it shows that it's probably not just a terminal bug.

**Comment by mogenslund** [comment]
I was able to reproduce it using the arrow keys. (I usually use jkli for navigation.) The arrow keys produce some longer escape sequences, so when holding down the key the sequence is more or less continues. I have commitet a fix that detects when the sequence is repeating. The problem seem to be only present for complex escape sequences like Arrow keys and F-keys etc.

**Comment by tom-adsfund** [comment]
Great! I'll keep this issue open for a couple of days in case there's any more on this.

**Comment by mogenslund** [comment]
I think I can close this issue now :-)
