### ISSUE TITLE
(doall (map inc [1 2 3])) evals to lazy seq

### ISSUE THREAD

**Issue by maacl** [mogenslund/liquid#30]
doall should force the sequence.

**Comment by mogenslund** [comment]
I think it does. It is just still a lazy sequence. If you compare with the repl, I think the repl applies a `pr-str` to the result, which prints the evaluated sequence. Try the following in a repl:

    (type (doall (map inc [1 2 3])))

it will evaluate to `clojure.lang.LazySeq`.

In Liquid try:

    (doall (map #(println %) [1 2 3])) 

Notice the sideeffect is executed!

Last. In Liquid do

    (pr-str (doall (map inc [1 2 3])))

Now you get the correct output.

I can change my code to apply `pr-str` automatically, but I think I prefer it as an explicit option to avoid printing endless sequences.

**Comment by mogenslund** [comment]
I think you have a point.

I will try out how CIDER handles my edge cases and adjust my local implementation accordingly and use it for some days to check if there are any unexpected side effects.
