### ISSUE TITLE
keybinding to swap main and eval window back and forth

### ISSUE THREAD

**Issue by BorisVSchmid** [mogenslund/liquid#32]
Right now, error messages and output show up in the smaller left-side window, and they format pretty poorly (as they expect more like a 50 column window). 

Would it be possible to have a shortcut key that swaps the content of the main and eval window back and forth? That would make quick inspection of the eval window's content easier.

I think ideally, the main window wouldnt be word-wrapped into the eval windows' column width, but rather keep its main window column width formatting (makes for mental easier referencing if your code doesn't suddenly look all different due to wrapping), and truncating what is visible in the eval window.

But thanks for making liquid. Using LightTable right now, but interested in this one :-).

**Comment by mogenslund** [comment]
Hi @BorisVSchmid 

If you type "M" (shift-m) a tmp buffer will be created with a copy of the content of the prompt buffer. I think you will find that useful.
Typing small letter "m" will switch back to the original buffer.
