### ISSUE TITLE
(editor/add-keybinding "dk.salza.liq.keymappings.normal" "f5" editor/kill-buffer)

### ISSUE THREAD

**Issue by akiz** [mogenslund/liquid#37]
Hi, 
In the cheat sheet there is "c-k" for killing the buffer. It does not work for me. So i tried to create new binding. But this freezes the app:
tested with two different configuration, one 1.1.0 on WSL Ubuntu
the second one 1.1.2 from windows powershell.

**Comment by mogenslund** [comment]
Hi @akiz 
Thank you very much! The C-k keybinding is a typo. It should have been C-w. I have updated the cheatsheet.
The editor/add-keybinding problem is a bug. When evaluating the expression in the editor it tries to display the output in the prompt area. But the output is the whole editor itself. I have fixed it now, so it just returns nil after adding the keybinding.

**Comment by akiz** [comment]
Thank you @mogenslund. This was my first real experience with Liquid. I am Emacs user so killing buffer and changing keybindings is first thing I do :).
