### ISSUE TITLE
terminal flashing

### ISSUE THREAD

**Issue by apparluk** [mogenslund/liquid#53]
UXTerm in reverse video when entering commands flashes INSERT.

**Comment by mogenslund** [comment]
Hi @apparluk 
Thank you for your report. I cannot reproduce it on my own computer. Does it not happen when you do not use reverse video?
Are you on Linux or Mac? (I only have Linux myself)
How do you run it? From a jar og with "clj -m liq.core" or something else?

**Comment by apparluk** [comment]
Factually INSERT briefly flashes on startup.

I first noticed it in UXTerm when reverse video was not enabled.

I'm running Linux, and it also occurs in konsole and xfce4-terminal.

https://github.com/mogenslund/liquid#installation

It occurs running either the clj or java commands under installation.

**Comment by apparluk** [comment]
In 2019 with ghc-7.8.4 I built yi-0.11.2.

I preferred the vim keymap.

https://hackage.haskell.org/package/yi

https://github.com/yi-editor/yi
The Haskell-Scriptable Editor (no longer maintained)

**Comment by apparluk** [comment]
The flashing also is present in [st](https://st.suckless.org/).

**Comment by mogenslund** [comment]
Ok. Thank you. I have done some experiments, without being able to reproduce it. I also tried to add some delays in the code, to slow down execution. I have a suspicion that intermediate buffers are being drawn and that I cannot observe it, because it happens too fast on my computer. I will continue with some more experiments following that path.

**Comment by apparluk** [comment]
my computer

Intel(R) Atom(TM) CPU N270 @1.60GHz
I GB RAM

**Comment by mogenslund** [comment]
Hi again
I have now tried on different machines, including a virtual machine with low specs. I still cannot reproduce it. Of cause rendering is slow on slow machines, but I do not know if it is just that, you are experiencing?
Maybe you can share a video of what happens? This will allow me to observe more precisely how and when it happens.

**Comment by apparluk** [comment]
SimpleScreenRecorder 0.4.2

UXTerm (reverse video)

[liquid.zip](https://github.com/mogenslund/liquid/files/5468214/liquid.zip)

**Comment by mogenslund** [comment]
Great! Thank you. I can see it now.
I have made a commit that should fix it.

**Comment by apparluk** [comment]
I'll close for now and check a new release when made.
