### ISSUE TITLE
Can't assume a "block" cursor

### ISSUE THREAD

**Issue by frou** [mogenslund/liquid#55]
Hi there - A lot of people (like me!) have their terminal configured to use an in-between cursor rather than a block/box cursor:

<img width="563" alt="Screenshot 2020-11-21 at 11 11 39" src="https://user-images.githubusercontent.com/172663/99875840-8219c280-2bea-11eb-9865-aabda173482b.png">

<img width="153" alt="Screenshot 2020-11-21 at 11 23 56" src="https://user-images.githubusercontent.com/172663/99876036-133d6900-2bec-11eb-924c-af00cba35919.png">

In Liquid, when moving around, and when typing, there is an additional block that flashes, which is distracting.

I think it's because Liquid's own code draws a "fake" block cursor?
https://github.com/mogenslund/liquid/blob/master/src/liq/tty_output.cljc#L97
https://github.com/mogenslund/liquid/blob/master/src/liq/tty_output.cljc#L117

How about making it possible to optionally disable that?

**Comment by mogenslund** [comment]
Hi @frou

I just tried with an in-between cursor and I see your point. I will add some kind of toggle soon.

/Mogens

**Comment by frou** [comment]
Thanks Mogens. BTW has the "Slider" concept been retired? I haven't used the editor that much yet, but I do remember hearing about that concept a while back.

**Comment by mogenslund** [comment]
Yes. I "retired" it. It was a bit "too clever". I more or less rewrote the whole editor in an attempt to make the internals more intuitive. Now lines in the buffer is represented as vectors of chars and texts as vectors of lines which better fits the mental model. If others should be able to contribute to the editor then "intuitive" is much better than "clever". I still struggle a bit though, making it easy to understand for others.

**Comment by mogenslund** [comment]
I have made a commit now. I have set the default to not use the block character hack, since this somehow works in all cases and made it an option to enable the previous behaviour using the code:

`(swap! liq.tty-output/settings assoc :liq.tty-output/cursor-draw-hack true)`

**Comment by frou** [comment]
Just tried it and the new default seems to be working nicely. Appreciated!

Not sure whether you're interested in hearing what causes people to try Liquid. But for me I'm a big Sublime Text user and have written dozens of (mostly private) plugins for it using Python. Problem is, that's the only place I use Python. I'd like to free the space in my brain used to remember the semantics and standard library of Python, and have an editor I can hack on using a language I'm actually enthusiastic about using!

**Comment by mogenslund** [comment]
Thanks for sharing. It is sort of the same reason why I created Liquid. I want to do everything in Clojure. Other than that it is just a bonus that almost anything created for the JVM can be sewn into the editor.
