### ISSUE TITLE
Docstring is misplaced

### ISSUE THREAD

**Issue by ericnormand** [mogenslund/liquid#7]
The docstring for the function at the following link should come before the argument vector.

https://github.com/mogenslund/liquid/blob/8d7f3a6f0adbbb048f09bf5ce08f199e9acec603/src/dk/salza/liq/editor.clj#L411

**Comment by mogenslund** [comment]
Your are right. Thank you. I will have that fixed :-)

**Comment by mogenslund** [comment]
I have fixed the docstring now.
